services:
  phpserver:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - vendor_volume:/var/www/html/vendor
    env_file:
      - .env
      - .env-local

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file:
      - .env
      - .env-local
    volumes:
     - db:/var/lib/postgresql/data

networks:
  academi-net:
    driver: bridge

volumes:
  db:
  vendor_volume: